# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Home Hero
  description: Home Hero Section
  icon: "title"
  tags: ["hero"]

# Defines the structure of this component, as well as the default values
blueprint:
  title: Google Bewertungen löschen
  subtitle: Spezialkanzlei für Reputationsschutz
  description: Negative Bewertungen und Verleumdungen bei Google, Kununu, Jameda, Tripadvisor, Trustpilot und anderen Portalen löschen lassen.
  slogan: Überlassen Sie Ihren Ruf nicht anderen!

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: Google Bewertungen löschen
  subtitle: Spezialkanzlei für Reputationsschutz
  description: Negative Bewertungen und Verleumdungen bei Google, Kununu, Jameda, Tripadvisor, Trustpilot und anderen Portalen löschen lassen.
  slogan: Überlassen Sie Ihren Ruf nicht anderen!

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
